# Generated by Django 6.0.1 on 2026-03-25 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('target_weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress_profile', to='accounts.member')),
            ],
        ),
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('logged_at', models.DateField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to='accounts.member')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
    ]
