# Generated by Django 6.0.2 on 2026-03-25 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_member_qr_token_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'General'), ('equipment', 'Equipment'), ('cleanliness', 'Cleanliness'), ('staff', 'Staff'), ('classes', 'Classes'), ('other', 'Other')], default='general', max_length=20)),
                ('message', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='accounts.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
