# Generated by Django 6.0.2 on 2026-03-24 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('goal', models.CharField(choices=[('bulk', 'Bulk'), ('cut', 'Cut'), ('maintain', 'Maintain'), ('strength', 'Strength')], default='maintain', max_length=20)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('days_per_week', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=100)),
                ('sets', models.PositiveIntegerField(default=3)),
                ('reps', models.CharField(max_length=50)),
                ('weight_note', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workoutday')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='workoutday',
            name='split',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='workouts.workoutsplit'),
        ),
        migrations.AlterUniqueTogether(
            name='workoutday',
            unique_together={('split', 'day_number')},
        ),
    ]
